### ISSUE TITLE
General notes on performance/behaviour

### ISSUE THREAD

**Issue by CameronBodine** [dbuscombe-usgs/dash_doodler_dev#2]
Just some general notes on two class doodling of grayscale images. I randomly picked 10 sonograms with varying contrast. I doodled each of them only once.

- Segmentation speed: Seems to segment doodles a bit faster then previous versions. Maybe 20-30s compared to 30-45s. But I didn't test rigorously.
- Accuracy of segmentation: It seems to do a better job the first time of doodling. Here is a [link](https://drive.google.com/file/d/15g7a6Try4eVUk1lkyFolpl-QSLRr7oDf/view?usp=sharing) to my images and doodles, if that is helpful.

FYI: Some funkiness encountered in this a previous versions:

- Using a stylus on touchscreen, sometimes the screen will pan around rather then draw doodles. Or worse, doodle and pan at the same time. I found that if I hit the 'Draw Open Freeform' button before each doodle, that seemed to fix it and force the stylus to make doodles instead of panning.

If there is anything else you need to know or want me to try, just lemme know!

**Comment by dbuscombe-usgs** [comment]
This makes sense, although I was definitely expecting a much bigger speed up than you are reporting (my segmentations are easily 3x - 5x faster than previous). It's doing less than a quarter of the previous number of operations .... but thanks, this is valuable

Not sure what to say about the stylus issues - is there a "sensitivity" setting on the pen? are certain browsers affected?
